export const PAGE_DEFAULTS = {
  home: {
    hero_badge: "Performance Marketing Specialist",
    hero_title_before: "Let's Grow Your Business Through",
    hero_title_highlight: "Smarter Digital Marketing.",
    hero_description: "Google Ads, Meta Ads, Conversion Tracking & Growth Strategy designed around measurable business results.",
    hero_primary_cta: "Book a Free Consultation",
    hero_secondary_cta: "View My Work",
    hero_image: "https://media.base44.com/images/public/6a8b03e54d231ed531b97b43/2e61e7de6_ovejite-gads.jpeg",
    roas: "4.8x",
    conversions: "+186%",
    trust_items: ["Performance Marketing","Data-Driven Strategy","Conversion Tracking","Growth Optimization"],
    platforms: ["Google Ads","Google Analytics","GTM","Meta","Shopify"],
    credibility_eyebrow: "Ready to grow?",
    credibility_title: "Ready to Improve Your Marketing Performance?",
    credibility_description: "Whether you're scaling ad spend, fixing conversion tracking, or building a growth strategy from scratch — it starts with understanding what's working and what isn't.",
    credibility_cta: "Let's Discuss Your Growth Strategy",
    services_eyebrow: "What I Do",
    services_title: "How I Help Businesses Grow",
    services_subtitle: "From advertising strategy to conversion tracking to continuous optimization — every service is built around measurable business outcomes.",
    services_cta: "Explore All Services",
    featured_sections: [
      {"eyebrow":"Google Ads","title":"Google Ads That Focus on Business Growth","services":["Search","Shopping","Performance Max"],"description":"Campaigns built around your business goals — not just clicks. From structure and targeting to continuous optimization and scaling.","cta":{"label":"Explore Google Ads Services","to":"/services/google-ads-management"},"visual":"chart"},
      {"eyebrow":"Tracking & Measurement","title":"Know Exactly What Your Marketing Is Doing","services":["GA4","GTM","Conversion Tracking","Server-Side Tracking"],"description":"Build accurate measurement systems so every campaign decision is based on reliable data.","cta":{"label":"Explore Tracking Services","to":"/services/conversion-tracking"},"visual":"flow"},
      {"eyebrow":"Landing Pages & CRO","title":"Turn More Clicks Into Customers","services":["Landing Pages","Funnels","CRO"],"description":"Improve the user journey from click to conversion. Better pages, better funnels, better results.","cta":{"label":"Improve Your Conversion Rate","to":"/services/landing-page-optimization"},"visual":"funnel"},
      {"eyebrow":"Growth Strategy","title":"Build a Connected Growth Strategy","services":["Google Ads","Meta Ads","Data","Optimization"],"description":"Connect advertising, data, conversion optimization, and business goals into one cohesive growth engine.","cta":{"label":"Let's Build Your Strategy","to":"/services/growth-strategy"},"visual":"ecosystem"}
    ],
    performance_eyebrow: "Data-Driven",
    performance_title: "Marketing Decisions Should Be Backed by Data.",
    performance_subtitle: "Every campaign, every optimization, every dollar — measured, analyzed, and improved. These are illustrative visualizations of the metrics that matter.",
    industries_eyebrow: "Industries",
    industries_title: "Built for Your Industry",
    industries_subtitle: "Different industries need different strategies. Here's how I approach the ones I work with most.",
    industries_cta: "Explore All Industries",
    case_studies_eyebrow: "Proof",
    case_studies_title: "Real Work. Real Strategy. Real Growth.",
    case_studies_subtitle: "Case studies showing the strategy, tracking, and optimization behind real results. New projects added as they're completed.",
    case_studies_cta: "View All Case Studies",
    process_eyebrow: "The Process",
    process_title: "How I Approach Growth",
    process_subtitle: "A structured, repeatable process that turns data into decisions and decisions into growth.",
    process_steps: [
      {"num":"01","title":"Understand","desc":"Learn about the business, goals, customers, and current marketing."},
      {"num":"02","title":"Measure","desc":"Build or improve tracking so decisions are based on accurate data."},
      {"num":"03","title":"Build","desc":"Create the campaign strategy, structure, targeting, and conversion system."},
      {"num":"04","title":"Optimize","desc":"Analyze performance and continuously improve efficiency."},
      {"num":"05","title":"Scale","desc":"Increase what works while protecting profitability."}
    ],
    about_title: "Meet the Marketer Behind the Strategy.",
    about_paragraph: "My approach connects advertising, data, and conversion optimization — because advertising works better when strategy, tracking, and conversion are connected.",
    about_cta: "Learn More About Me",
    resources_eyebrow: "Insights & Resources",
    resources_title: "Insights & Resources",
    resources_subtitle: "Practical guides on Google Ads, Meta Ads, conversion tracking, GA4, and growth strategy — written for marketers and business owners who want to make better decisions.",
    resources_cta: "Explore All Resources",
    final_title: "Let's Talk About Better Results.",
    final_description: "If you're looking to improve your paid advertising, fix your conversion tracking, or build a stronger growth strategy, let's start with a conversation.",
    final_cta: "Book a Call"
  },
  about: {
    eyebrow:"About",
    title:"Meet the Marketer Behind the Strategy.",
    cta:"Let's Work Together",
    philosophy:["Better data leads to better decisions.","Know what your marketing is actually doing.","Advertising works better when strategy, tracking, and conversion are connected.","Growth comes from continuous improvement, not one-time fixes."]
  },
  contact: {
    eyebrow:"Contact",
    title:"Let's Start a Conversation",
    description:"Tell me about your business and your goals. I'll get back to you within 24 hours.",
    form_title:"Send a Message"
  },
  services: { eyebrow:"Services", title:"How I Help Businesses Grow", subtitle:"From advertising strategy to conversion tracking to continuous optimization — every service is built around measurable business outcomes." },
  industries: { eyebrow:"Industries", title:"Built for Your Industry", subtitle:"Different industries need different strategies. Here's how I approach the ones I work with most." },
  "case-studies": { eyebrow:"Case Studies", title:"Real Work. Real Strategy. Real Growth.", subtitle:"Case studies showing the strategy, tracking, and optimization behind real results. New projects added as they're completed." },
  resources: { eyebrow:"Resources", title:"Insights & Resources", subtitle:"Practical guides on Google Ads, Meta Ads, conversion tracking, GA4, and growth strategy." },
  privacy: { content_markdown:"Privacy Policy\n\nLast updated: {{date}}\n\nOvejite.me respects your privacy. This policy explains how we collect, use, and protect your information.\n\n## Information We Collect\n\nWhen you submit a contact form, we collect the information you provide: name, email, phone, company, website, budget, service interest, and message.\n\n## How We Use Your Information\n\nWe use your information to respond to inquiries, provide consulting services, and communicate about marketing strategy. We never sell or share your data with third parties.\n\n## Analytics\n\nWe may use Google Analytics, Google Tag Manager, and Meta Pixel to understand website usage. These tools collect anonymous usage data.\n\n## Contact\n\nFor privacy questions, please reach out through the contact page." },
  terms: { content_markdown:"Terms of Service\n\nLast updated: {{date}}\n\nBy using Ovejite.me, you agree to these terms.\n\n## Services\n\nOvejite provides digital marketing consulting services including Google Ads, Meta Ads, conversion tracking, and growth strategy. Specific deliverables are agreed upon per engagement.\n\n## No Guarantees\n\nWhile we strive for excellent results, marketing outcomes depend on many factors outside our control. We do not guarantee specific performance metrics.\n\n## Intellectual Property\n\nAll content on this site is the property of Ovejite.me. Case studies and resources are provided for informational purposes.\n\n## Contact\n\nFor questions about these terms, please reach out through the contact page." }
};
